# .github/workflows/build.yml

name: Build and Test Molly's asset manager

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libgl1-mesa-dev xorg-dev
    
    - name: Configure project
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build test target
      run: cmake --build build --target molly_tests

    - name: Run tests
      run: ctest --test-dir build --output-on-failure